name = "arctic"
description = "A friendly web framework for fast response times and a lightweight or serverless backend, written in Gleam!"
docs_url = "https://hexdocs.pm/arctic/"
repo_url = "https://github.com/RyanBrewer317/arctic"
category = ""
