name = "check_maybe_div_by_zero"
description = "Checks gleam source code for potential division by zero in a hacky way :D"
docs_url = "https://hexdocs.pm/check_maybe_div_by_zero/"
repo_url = "https://github.com/inoas/check_maybe_div_by_zero"
category = ""
