name = "dnalg"
description = "DNAlg is a DNA manipulation library written in Gleam. It can be used as a library for your own Gleam programs, or a command line program!"
docs_url = "https://hexdocs.pm/dnalg/"
repo_url = "https://github.com/VoxelMC/dnalg-gleam"
category = ""
