name = "formz_lustre"
description = "Lustre widgets and field definitions for the formz library."
docs_url = "https://hexdocs.pm/formz_lustre/"
repo_url = "https://github.com/bentomas/formz"
category = ""
