name = "glemtext"
description = "A small library for parsing Gemini's gemtext. Runs on both Erlang and JS"
docs_url = "https://hexdocs.pm/glemtext/"
repo_url = "https://github.com/myrkvi/glemtext"
category = ""
