name = "glimpse"
description = "Package loader and (theoretically) typechecker for glance"
docs_url = "https://hexdocs.pm/glimpse/"
repo_url = "https://github.com/dusty-phillips/glimpse"
category = ""
