name = "gtransducer"
description = "A transducer library for composable algorithmic transformations."
docs_url = "https://hexdocs.pm/gtransducer/"
repo_url = "https://github.com/nohzafk/gtransducer"
category = ""
