name = "ieee_float"
description = "Gleam library that provides an IEEE 754 compliant float type."
docs_url = "https://hexdocs.pm/ieee_float/"
repo_url = "https://github.com/richard-viney/ieee_float"
category = ""
