name = "jot_to_lustre"
description = "Convert jot documents or strings to lustre/element/html elements"
docs_url = "https://hexdocs.pm/jot_to_lustre/"
repo_url = "https://github.com/ray-delossantos/jot_to_lustre"
category = ""
