name = "jotkey"
description = "Convert jot documents to lustre elements. Can convert to custom renderers"
docs_url = "https://hexdocs.pm/jotkey/"
repo_url = "https://github.com/ray-delossantos/jotkey"
category = ""
