name = "postglide"
description = "Gleam bindings to PGlite, a WASM build of Postgres for client-side browser applications"
docs_url = "https://hexdocs.pm/postglide/"
repo_url = "https://github.com/george-grec/postglide"
category = ""
