name = "secp256k1_gleam"
description = "A Gleam wrapper for the secp256k1 library"
docs_url = "https://hexdocs.pm/secp256k1_gleam/"
repo_url = "https://github.com/gusinacio/secp256k1_gleam"
category = ""
