name = "shine_tree"
description = "A `FingerTree` implementation for general purpose functional programming in Gleam!"
docs_url = "https://hexdocs.pm/shine_tree/"
repo_url = "https://github.com/shine-coders/shine_tree"
category = ""
